/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bioreactorsimulationsoftware;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author yegor
 */
public class BioConVSTime extends javax.swing.JFrame {

    /**
     * Creates new form BioConVSTime
     */
    public BioConVSTime() {
        initComponents();
        
        this.setBounds(0, 0, 650, 450);
    }
    
    //This method calculates X(t) at each time starting from 0 until the fermentation time
    public void createPlot(double time, double waterVol, double Xmax, double Xo, double U) {
        
        System.out.print("\n");
        
        double finBioCon, timeSum=0, XTime;

        
        // Create a series of data points (x, y)
        XYSeries series = new XYSeries("");
        
        while(timeSum<=time){
            
            XTime = Xmax/(1+((Xmax-Xo)/Xo)*Math.exp(-U*timeSum));
            
            finBioCon = XTime / waterVol;
            
            series.add(timeSum, finBioCon);
            
            timeSum+=0.1;
            
            //Debug
            System.out.println("X("+timeSum+")="+finBioCon);
            
        }
        

        // Create a dataset using the series
        XYSeriesCollection dataset = new XYSeriesCollection(series);

        // Create the chart
        JFreeChart chart = ChartFactory.createXYLineChart(
                "Biomass concentration versus Fermentation Time",  // Chart title
                "Time (h)",            // X Axis label
                "Biomass Concentration (g/L)",            // Y Axis label
                dataset,             // Dataset
                org.jfree.chart.plot.PlotOrientation.VERTICAL, // Plot orientation
                true,                // Show legend
                true,                // Use tooltips
                false                // Configure chart to generate URLs
        );

        // Create a ChartPanel (which is a Swing component to hold the chart)
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(600, 400));  // Set size of the chart panel

        // Add the ChartPanel to the content pane of the JFrame
        getContentPane().add(chartPanel);
        
        //
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BioConVSTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BioConVSTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BioConVSTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BioConVSTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BioConVSTime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
