/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bioreactorsimulationsoftware;

/**
 *
 * @author yegor
 */

import java.text.DecimalFormat;

public class BioreactorSimulationProgram extends javax.swing.JFrame {

    /**
     * Creates new form BioreactorSimulationProgram
     */
    public BioreactorSimulationProgram() {
        initComponents();
        
        this.setBounds(0, 0, 525, 720);
        
        this.setTitle("Bioethanol Simulation");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        iniBioConTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        iniSubConTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        returnOnInvestmentTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        runButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        watVolTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        finBioConTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        finEthConTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rateOfEthConTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        yieldOfEthTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        costOfSubTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        revenueTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        totalProductionCostsTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        profitTextField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Parameters");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 0, 190, 30);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel2.setText("Initial Biomass Concentration:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 320, 30);

        iniBioConTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        getContentPane().add(iniBioConTextField);
        iniBioConTextField.setBounds(330, 50, 100, 30);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel5.setText("g");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 90, 30, 30);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel4.setText("Initial Substrate Concentration:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 90, 340, 30);

        iniSubConTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        getContentPane().add(iniSubConTextField);
        iniSubConTextField.setBounds(350, 90, 100, 30);

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel12.setText("g/L");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 330, 40, 30);

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel6.setText("Time:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 130, 60, 28);

        timeTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        getContentPane().add(timeTextField);
        timeTextField.setBounds(70, 130, 96, 30);

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel7.setText("h");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(170, 130, 20, 30);

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel8.setText("Water Volume:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 170, 160, 30);

        returnOnInvestmentTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        getContentPane().add(returnOnInvestmentTextField);
        returnOnInvestmentTextField.setBounds(250, 650, 100, 30);

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel9.setText("L");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(280, 170, 20, 30);

        runButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        runButton.setText("Run the simulation");
        getContentPane().add(runButton);
        runButton.setBounds(10, 220, 248, 40);

        resetButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton);
        resetButton.setBounds(270, 220, 140, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 270, 520, 10);

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("Results");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 280, 120, 40);

        jLabel23.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel23.setText("Total production costs:");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(10, 570, 250, 28);

        watVolTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        getContentPane().add(watVolTextField);
        watVolTextField.setBounds(170, 170, 100, 30);

        jLabel16.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel16.setText("g/L/h");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(460, 410, 60, 30);

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel13.setText("Final Ethanol Concentration:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 370, 310, 25);

        finBioConTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        getContentPane().add(finBioConTextField);
        finBioConTextField.setBounds(330, 330, 100, 30);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel3.setText("g/L");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 50, 40, 30);

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel15.setText("Rate of Ethanol Concentration:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 410, 340, 28);

        finEthConTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        getContentPane().add(finEthConTextField);
        finEthConTextField.setBounds(320, 370, 100, 30);

        jLabel28.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel28.setText("%");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(360, 650, 30, 30);

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel17.setText("Yield of Ethanol:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 450, 180, 28);

        rateOfEthConTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        getContentPane().add(rateOfEthConTextField);
        rateOfEthConTextField.setBounds(350, 410, 100, 30);

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel14.setText("g/L");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(430, 370, 40, 30);

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel11.setText("Final Biomass Concentration:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 330, 320, 28);

        jLabel19.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel19.setText("Cost of Subtrate:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(10, 490, 190, 28);

        jLabel21.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel21.setText("Revenue:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(10, 530, 110, 28);

        jLabel25.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel25.setText("Profit:");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(10, 610, 70, 28);

        jLabel27.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel27.setText("Return on investment:");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(10, 650, 240, 28);

        yieldOfEthTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        getContentPane().add(yieldOfEthTextField);
        yieldOfEthTextField.setBounds(190, 450, 100, 30);

        jLabel18.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel18.setText("g/g");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(300, 450, 40, 30);

        costOfSubTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        getContentPane().add(costOfSubTextField);
        costOfSubTextField.setBounds(200, 490, 100, 30);

        jLabel20.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel20.setText("$");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(310, 490, 20, 30);

        revenueTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        getContentPane().add(revenueTextField);
        revenueTextField.setBounds(120, 530, 100, 30);

        jLabel22.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel22.setText("$");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(230, 530, 20, 30);

        totalProductionCostsTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        getContentPane().add(totalProductionCostsTextField);
        totalProductionCostsTextField.setBounds(260, 570, 100, 30);

        jLabel24.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel24.setText("$");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(370, 570, 20, 30);

        profitTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        getContentPane().add(profitTextField);
        profitTextField.setBounds(80, 610, 100, 30);

        jLabel26.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel26.setText("$");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(190, 610, 20, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        iniBioConTextField.setText(null);
        iniSubConTextField.setText(null);
        timeTextField.setText(null);
        watVolTextField.setText(null);
        
        finBioConTextField.setText(null);
        finEthConTextField.setText(null);
        rateOfEthConTextField.setText(null);
        yieldOfEthTextField.setText(null);
        costOfSubTextField.setText(null);
        revenueTextField.setText(null);
        totalProductionCostsTextField.setText(null);
        profitTextField.setText(null);
        returnOnInvestmentTextField.setText(null);
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BioreactorSimulationProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BioreactorSimulationProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BioreactorSimulationProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BioreactorSimulationProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BioreactorSimulationProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField costOfSubTextField;
    private javax.swing.JTextField finBioConTextField;
    private javax.swing.JTextField finEthConTextField;
    private javax.swing.JTextField iniBioConTextField;
    private javax.swing.JTextField iniSubConTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField profitTextField;
    private javax.swing.JTextField rateOfEthConTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField returnOnInvestmentTextField;
    private javax.swing.JTextField revenueTextField;
    private javax.swing.JButton runButton;
    private javax.swing.JTextField timeTextField;
    private javax.swing.JTextField totalProductionCostsTextField;
    private javax.swing.JTextField watVolTextField;
    private javax.swing.JTextField yieldOfEthTextField;
    // End of variables declaration//GEN-END:variables
}
