/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amyae
 */

import javax.swing.event.*;

public class bioethanolSimProgram extends javax.swing.JFrame {

    /**
     * Creates new form bioethanolSimProgram
     */
    public bioethanolSimProgram() {
        initComponents();
        
        this.setSize(400, 300);
        
        phSlider.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                // Update the text field with the slider's value
                phTextField.setText(String.valueOf(phSlider.getValue()));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        iSCTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tempTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        waterAmoTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        phSlider = new javax.swing.JSlider();
        phTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Initial substrate concentration:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 190, 20);
        getContentPane().add(iSCTextField);
        iSCTextField.setBounds(190, 0, 64, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("gram");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 0, 40, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Temperature:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 30, 90, 20);
        getContentPane().add(tempTextField);
        tempTextField.setBounds(90, 30, 64, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("°C");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 30, 37, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Water amount:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 60, 100, 20);
        getContentPane().add(waterAmoTextField);
        waterAmoTextField.setBounds(100, 60, 71, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("liter");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 60, 37, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("pH:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 90, 37, 16);

        phSlider.setMaximum(14);
        phSlider.setValue(7);
        getContentPane().add(phSlider);
        phSlider.setBounds(30, 90, 200, 20);

        phTextField.setText("7");
        getContentPane().add(phTextField);
        phTextField.setBounds(230, 90, 30, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bioethanolSimProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bioethanolSimProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bioethanolSimProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bioethanolSimProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bioethanolSimProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField iSCTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSlider phSlider;
    private javax.swing.JTextField phTextField;
    private javax.swing.JTextField tempTextField;
    private javax.swing.JTextField waterAmoTextField;
    // End of variables declaration//GEN-END:variables
}
