/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.bioreactorsimsoftware;


/**
 *
 * @author amyae
 */

import java.text.DecimalFormat;

public class bioethanolSimProgram extends javax.swing.JFrame {

    /**
     * Creates new form bioethanolSimProgram
     */
    public bioethanolSimProgram() {
        initComponents();
        
        this.setSize(400, 462);
        
        this.setTitle("Bioethanol Simulation");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        iSConTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tempTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        waterAmoTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        phTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        runButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        ethConTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        iBConTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        rOEthConTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bioGroTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        yieCoeTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        costTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Initial substrate concentration:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 190, 20);
        getContentPane().add(iSConTextField);
        iSConTextField.setBounds(210, 40, 64, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("g");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 40, 10, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Temperature:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 90, 20);
        getContentPane().add(tempTextField);
        tempTextField.setBounds(100, 70, 64, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("°C");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 70, 37, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Water amount:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 100, 100, 20);
        getContentPane().add(waterAmoTextField);
        waterAmoTextField.setBounds(110, 100, 71, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("L");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 100, 10, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("pH:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 160, 37, 16);

        phTextField.setText("7");
        getContentPane().add(phTextField);
        phTextField.setBounds(40, 160, 40, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Parameters");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 0, 120, 32);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Results");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 240, 80, 32);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Ethanol concentration:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 280, 140, 20);

        runButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        runButton.setText("Run the simulation");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });
        getContentPane().add(runButton);
        runButton.setBounds(10, 190, 160, 30);

        resetButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton);
        resetButton.setBounds(180, 190, 75, 30);
        getContentPane().add(ethConTextField);
        ethConTextField.setBounds(160, 280, 71, 22);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("g/L");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(240, 280, 20, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Initial biomass concentration:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 130, 190, 20);
        getContentPane().add(iBConTextField);
        iBConTextField.setBounds(200, 130, 71, 22);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("g/L");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(280, 130, 30, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 230, 400, 3);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Rate of ethanol concentration:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 310, 190, 20);
        getContentPane().add(rOEthConTextField);
        rOEthConTextField.setBounds(210, 310, 71, 22);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("g/L/h");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(290, 310, 40, 20);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Biomass growth:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 340, 110, 20);
        getContentPane().add(bioGroTextField);
        bioGroTextField.setBounds(120, 340, 64, 22);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("g/g");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(190, 340, 30, 20);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Yield coefficient:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 370, 110, 20);
        getContentPane().add(yieCoeTextField);
        yieCoeTextField.setBounds(120, 370, 64, 22);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("g/g");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(190, 370, 30, 20);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Cost:");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(10, 400, 40, 20);
        getContentPane().add(costTextField);
        costTextField.setBounds(50, 400, 64, 22);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("€");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(120, 400, 10, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        iSConTextField.setText(null);
        tempTextField.setText(null);
        waterAmoTextField.setText(null);
        iBConTextField.setText(null);
        phTextField.setText("7");
        
        ethConTextField.setText(null);
        rOEthConTextField.setText(null);
        bioGroTextField.setText(null);
        yieCoeTextField.setText(null);
        costTextField.setText(null);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        // TODO add your handling code here:
        // Create decimalformat instance
        DecimalFormat df = new DecimalFormat("#.###");

        // Ethanol concentration calculation
        double iSC= Double.parseDouble(iSConTextField.getText());
        double waterAmo= Double.parseDouble(waterAmoTextField.getText());
        
        double  bioEthCon= (46*iSC)/(90*waterAmo);
        ethConTextField.setText(String.valueOf(df.format(bioEthCon)));

        // Yield coeff calculation
        double iniBioCon = Double.parseDouble(iBConTextField.getText());

        double yieldCoeffResult = iniBioCon/iSC;
        yieCoeTextField.setText(String.valueOf(df.format(yieldCoeffResult)));

        // Maximum carrying capacity(Xm)
        double Xm = yieldCoeffResult*iSC*waterAmo;

        //Specific growth rate
        double temp = Double.parseDouble(tempTextField.getText());
        double ph = Double.parseDouble(phTextField.getText());

        double sGR = 0.0013*(iSC/(0.35+iSC))*Math.pow((temp-7.5),2)*Math.exp(-0.55*Math.pow((ph-5.5),2));

        //Final biomass concentration
        double fBC = (1-(sGR/0.45))*Xm;
        bioGroTextField.setText(String.valueOf(df.format(fBC)));

        //Product formation kinetics
        double rPP = 5.5*sGR*fBC+0.5*fBC;
        rOEthConTextField.setText(String.valueOf(df.format(rPP)));

        //Cost analysis
        double cost = waterAmo*0.33+iSC*0.0012+iniBioCon*0.20;
        costTextField.setText(String.valueOf(df.format(cost)));
    }//GEN-LAST:event_runButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bioethanolSimProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bioethanolSimProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bioethanolSimProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bioethanolSimProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bioethanolSimProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bioGroTextField;
    private javax.swing.JTextField costTextField;
    private javax.swing.JTextField ethConTextField;
    private javax.swing.JTextField iBConTextField;
    private javax.swing.JTextField iSConTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField phTextField;
    private javax.swing.JTextField rOEthConTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton runButton;
    private javax.swing.JTextField tempTextField;
    private javax.swing.JTextField waterAmoTextField;
    private javax.swing.JTextField yieCoeTextField;
    // End of variables declaration//GEN-END:variables
}
